version: "3.9"

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
      # - wordpress_data:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9100:9000"
      - "8100:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    image: mariadb:10.6.0-focal
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_here
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress_password_here
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password_here
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped
  
networks:
  inception:
    driver: bridge

volumes:
  portainer_data:
  mariadb_data:
  wordpress_data:
